### ISSUE TITLE
Support Text2Speech + Speech2Text Commands

### ISSUE THREAD

**Issue by quachtina96** [willowjar/scratchNLP#4]
**How might a user actually use the speech blocks?**
When i say TEXT, <Action List>
When you hear TEXT,  <Action List>
Say TEXT
Speak TEXT

**Speech2Text**
_listenAndWait_ - command: Wait for the user to say something and store what they said into the speech 

- reporter
- Listen and wait
- Wait for a response
- wait for a reply
- wait until you hear speech

_getSpeech_ - reporter

- Det speech
- What you heard
- What i said
- What was said
- Det the reply
- Det the response

_whenIHear:_ 

- when you hear
- When i say

 
**Text2Speech**
_speakAndWait:_

- Say TEXT // Here making the explicit choice to override what say refers to. (speak instead of actual say)
- Say TEXT out loud
- Speak TEXT
- Tell me TEXT
- Voice TEXT

_setVoice:_
- Change your voice to be NEW_VOICE
- Change your voice to NEW_VOICE
- Set voice to NEW_VOICE
- Use the NEW_VOICE voice.
- switch voice to NEW_VOICE.

_setLanguage:_

- talk in NEW_LANGUAGE
- Change the language to NEW_LANGUAGE
- Set language to NEW_LANGUAGE
- Use the NEW_LANGUAGE language
- switch language to NEW_LANGUAGE

**Comment by quachtina96** [comment]
in order to support these commands we need to

- [ ] add the language to the lexicon
- [ ] add support for extracting phrases to say and adding them to the grammar dynamically
- [ ] implement the semantic rules

**Comment by quachtina96** [comment]
@karaluo09 as of commit 00e66e89450e1879a704ddb5b3d65bc18fe9c3e6 the following "complex speech" test cases don't work anymore...

**when you hear hi scratch say hi friend thats it**
expected: '{'variables': {}, 'lists': {}, 'scripts': [[['whenIHear', 'hi scratch'], ['speakAndWait:', 'hi friend']]]}'
got: 'I don't understand.'

**when i say meow to me play the meow sound thats it**
expected: '{'variables': {}, 'lists': {}, 'scripts': [[['whenIHear', 'meow to me'], ['doPlaySoundAndWait', 'meow']]]}'
got: 'I don't understand.'

**when you hear hello say goodbye thats it
**
expected: '{'variables': {}, 'lists': {}, 'scripts': [[['whenIHear', 'hello'], ['speakAndWait:', 'goodbye']]]}'
got: 'I don't understand.'

@karaluo09 the following basic "speech" test cases don't work anymore...

Exception: Failed to parse the sentence: speak hello
I don't understand.
[VALIDATION] FAILURE:
expected: '{'variables': {}, 'lists': {}, 'scripts': [['speakAndWait:', 'hello']]}'
got: 'I don't understand.'

> set accent to russian
Traceback (most recent call last):
  File "semantic.py", line 275, in run_repl
    tree = parse_input_str(input_str, scratch)
  File "semantic.py", line 78, in parse_input_str
    raise Exception("Failed to parse the sentence: " + input_str)
Exception: Failed to parse the sentence: set accent to russian
I don't understand.
[VALIDATION] FAILURE:
expected: '{'variables': {}, 'lists': {}, 'scripts': [['setLanguage:', 'russian']]}'
